In [21]:
import pandas as pd
df = pd.read_csv('food_orders_data.csv')
df.head(30)

    order_id    dish             location           order_time
0          1   Tacos             Downtown  2026-06-06 16:21:00
1          2   Sushi             Downtown  2026-06-01 19:57:00
2          3   Pasta             Downtown  2026-06-01 11:35:00
3          4   Salad             Downtown  2026-06-06 03:06:00
4          5   Pasta            Tech Park  2026-06-01 15:13:00
5          6   Sushi              Suburbs  2026-06-07 19:23:00
6          7   Tacos  University District  2026-06-03 10:14:00
7          8  Burger  University District  2026-06-03 01:02:00
8          9   Pasta  University District  2026-06-05 07:22:00
9         10   Sushi            Tech Park  2026-06-07 04:08:00
10        11   Pizza              Suburbs  2026-06-05 09:41:00
11        12   Salad              Suburbs  2026-06-04 13:14:00
12        13   Pizza             Downtown  2026-06-06 15:16:00
13        14   Curry              Suburbs  2026-06-07 08:38:00
14        15   Pasta            Tech Park  2026-06-06 08:04:00
15        16   Pizza  University District  2026-06-06 04:24:00
16        17  Burger             Downtown  2026-06-04 22:47:00
17        18   Curry             Downtown  2026-06-05 12:30:00
18        19  Burger            Tech Park  2026-06-05 09:50:00
19        20   Tacos  University District  2026-06-01 05:22:00
20        21   Pasta             Downtown  2026-06-01 18:20:00
21        22   Pasta              Suburbs  2026-06-01 13:03:00
22        23   Salad             Downtown  2026-06-01 08:50:00
23        24   Sushi             Downtown  2026-06-05 10:07:00
24        25   Salad            Tech Park  2026-06-01 03:22:00
25        26   Salad  University District  2026-06-02 00:52:00
26        27   Sushi            Tech Park  2026-06-05 11:59:00
27        28  Burger             Downtown  2026-06-01 02:26:00
28        29   Pasta  University District  2026-06-05 06:51:00
29        30   Salad            Tech Park  2026-06-07 11:48:00

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    1000 non-null   int64
 1   dish        1000 non-null   object
 2   location    1000 non-null   object
 3   order_time  1000 non-null   object
dtypes: int64(1), object(3)
memory usage: 31.4+ KB

In [23]:
df.columns

Index(['order_id', 'dish', 'location', 'order_time'], dtype='object')

In [25]:
df.describe()

          order_id
count  1000.000000
mean    500.500000
std     288.819436
min       1.000000
25%     250.750000
50%     500.500000
75%     750.250000
max    1000.000000